### ISSUE TITLE
fix example config

### ISSUE THREAD

**Issue by dpinol** [awebdeveloper/pre-commit-tslint#2]
Instead of 'sha'
```
-   repo: git://github.com/awebdeveloper/pre-commit-tslint/
        sha: ''  # Use the sha or tag you want to point at
```
it should be 'rev'
```
-   repo: git://github.com/awebdeveloper/pre-commit-tslint/
        rev: ''  # Use the sha or tag you want to point at
```

In my case, I also had to add typescript to additional_dependencies
`            additional_dependencies: ['tslint@5.0.0', 'typescript]
`

Otherwise, I got:
```
tslint...................................................................Failed
hookid: tslint

internal/modules/cjs/loader.js:803
    throw err;
    ^

Error: Cannot find module 'typescript'
Require stack:
- /Users/dani/.cache/pre-commit/repo17lc0toy/node_env-default/lib/node_modules/tslint/lib/linter.js
- /Users/dani/.cache/pre-commit/repo17lc0toy/node_env-default/lib/node_modules/tslint/lib/tslintCli.js
- /Users/dani/.cache/pre-commit/repo17lc0toy/node_env-default/lib/node_modules/tslint/bin/tslint
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:800:15)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
```

**Comment by thomaskisler** [comment]
I also had the problem of the missing additional dependency.

**Comment by awebdeveloper** [comment]
@thomaskisler what missing dependency issue you had
